_current_progress_remaining:
    value: 1
_custom_logger:
    value: "False"
_episode_num:
    value: 0
_last_episode_starts:
    value: '[ True  True  True  True  True  True  True  True]'
_last_obs:
    value: |-
        [[ 1.40717196  1.00394736 -0.00811645 ...  0.          0.
           0.        ]
         [ 1.39040059  1.00678425  0.00174286 ...  0.          0.
           0.        ]
         [ 1.39811541  1.00938368 -0.00675366 ...  0.          0.
           0.        ]
         ...
         [ 1.39930361  0.9920745   0.00933704 ...  0.          0.
           0.        ]
         [ 1.40027601  1.00388984  0.00304993 ...  0.          0.
           0.        ]
         [ 1.397839    1.00247399  0.00311629 ...  0.          0.
           0.        ]]
_last_original_obs:
    value: None
_logger:
    value: <stable_baselines3.common.logger.Logger object at 0x114a72270>
_n_updates:
    value: 0
_num_timesteps_at_start:
    value: 0
_stats_window_size:
    value: 100
_total_timesteps:
    value: 500000
_vec_normalize_env:
    value: None
_wandb:
    value:
        cli_version: 0.22.3
        e:
            yb33kxlrqxcobv7d4foyyljjj6ug0br2:
                apple:
                    ecpuCores: 4
                    gpuCores: 16
                    memoryGb: 24
                    name: Apple M4 Pro
                    pcpuCores: 8
                    ramTotalBytes: "25769803776"
                args:
                    - --env-id
                    - Humanoid-v5
                    - --total-timesteps
                    - "500000"
                    - --n-envs
                    - "8"
                    - --wandb
                    - --algo
                    - sac
                codePath: src/train.py
                codePathLocal: src/train.py
                cpu_count: 12
                cpu_count_logical: 12
                disk:
                    /:
                        total: "994662584320"
                        used: "360235175936"
                email: matteo.calabria01@gmail.com
                executable: /Users/matteo/Documents/01 Projects/hri-playground/.venv/bin/python3
                git:
                    commit: 7b75800caa5880255e57f155bf6eadedca6e01d5
                    remote: git@github.com:maedmatt/hri-playground.git
                host: MacBookPro
                memory:
                    total: "25769803776"
                os: macOS-26.0.1-arm64-arm-64bit-Mach-O
                program: /Users/matteo/Documents/01 Projects/hri-playground/src/train.py
                python: CPython 3.13.8
                root: /Users/matteo/Documents/01 Projects/hri-playground
                startedAt: "2025-11-10T16:39:46.105711Z"
                writerId: yb33kxlrqxcobv7d4foyyljjj6ug0br2
        m: []
        python_version: 3.13.8
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 3
                - 13
                - 16
                - 22
                - 35
            "4": 3.13.8
            "5": 0.22.3
            "12": 0.22.3
            "13": darwin-arm64
action_noise:
    value: None
action_space:
    value: Box(-0.4, 0.4, (17,), float32)
actor:
    value: |-
        Actor(
          (features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (latent_pi): Sequential(
            (0): Linear(in_features=348, out_features=256, bias=True)
            (1): ReLU()
            (2): Linear(in_features=256, out_features=256, bias=True)
            (3): ReLU()
          )
          (mu): Linear(in_features=256, out_features=17, bias=True)
          (log_std): Linear(in_features=256, out_features=17, bias=True)
        )
algo:
    value: sac
batch_norm_stats:
    value: '[]'
batch_norm_stats_target:
    value: '[]'
batch_size:
    value: 256
buffer_size:
    value: 1000000
critic:
    value: |-
        ContinuousCritic(
          (features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (qf0): Sequential(
            (0): Linear(in_features=365, out_features=256, bias=True)
            (1): ReLU()
            (2): Linear(in_features=256, out_features=256, bias=True)
            (3): ReLU()
            (4): Linear(in_features=256, out_features=1, bias=True)
          )
          (qf1): Sequential(
            (0): Linear(in_features=365, out_features=256, bias=True)
            (1): ReLU()
            (2): Linear(in_features=256, out_features=256, bias=True)
            (3): ReLU()
            (4): Linear(in_features=256, out_features=1, bias=True)
          )
        )
critic_target:
    value: |-
        ContinuousCritic(
          (features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (qf0): Sequential(
            (0): Linear(in_features=365, out_features=256, bias=True)
            (1): ReLU()
            (2): Linear(in_features=256, out_features=256, bias=True)
            (3): ReLU()
            (4): Linear(in_features=256, out_features=1, bias=True)
          )
          (qf1): Sequential(
            (0): Linear(in_features=365, out_features=256, bias=True)
            (1): ReLU()
            (2): Linear(in_features=256, out_features=256, bias=True)
            (3): ReLU()
            (4): Linear(in_features=256, out_features=1, bias=True)
          )
        )
device:
    value: cpu
ent_coef:
    value: auto
ent_coef_optimizer:
    value: |-
        Adam (
        Parameter Group 0
            amsgrad: False
            betas: (0.9, 0.999)
            capturable: False
            decoupled_weight_decay: False
            differentiable: False
            eps: 1e-08
            foreach: None
            fused: None
            lr: 0.0003
            maximize: False
            weight_decay: 0
        )
env:
    value: <stable_baselines3.common.vec_env.subproc_vec_env.SubprocVecEnv object at 0x1126aeba0>
env_id:
    value: Humanoid-v5
ep_info_buffer:
    value: deque([], maxlen=100)
ep_success_buffer:
    value: deque([], maxlen=100)
gamma:
    value: 0.99
gradient_steps:
    value: 1
learning_rate:
    value: 0.0003
learning_starts:
    value: 100
log_ent_coef:
    value: tensor([0.], requires_grad=True)
lr_schedule:
    value: FloatSchedule(ConstantSchedule(val=0.0003))
n_envs:
    value: 8
n_steps:
    value: 1
num_timesteps:
    value: 0
observation_space:
    value: Box(-inf, inf, (348,), float64)
optimize_memory_usage:
    value: "False"
policy:
    value: MlpPolicy
policy_class:
    value: <class 'stable_baselines3.sac.policies.SACPolicy'>
policy_kwargs:
    value: '{''use_sde'': False}'
replay_buffer:
    value: <stable_baselines3.common.buffers.ReplayBuffer object at 0x112738440>
replay_buffer_class:
    value: <class 'stable_baselines3.common.buffers.ReplayBuffer'>
replay_buffer_kwargs:
    value: '{}'
sde_sample_freq:
    value: -1
seed:
    value: 42
start_time:
    value: 1762792786966572000
target_entropy:
    value: -17
target_update_interval:
    value: 1
tau:
    value: 0.005
tensorboard_log:
    value: runs/tensorboard
total_timesteps:
    value: 500000
train_freq:
    value: 'TrainFreq(frequency=1, unit=<TrainFrequencyUnit.STEP: ''step''>)'
use_sde:
    value: "False"
use_sde_at_warmup:
    value: "False"
verbose:
    value: 0
