_current_progress_remaining:
    value: 1
_custom_logger:
    value: "False"
_episode_num:
    value: 0
_last_episode_starts:
    value: '[ True  True  True  True  True  True  True  True]'
_last_obs:
    value: |-
        [[ 1.39081947  0.99033055  0.0062654  ...  0.          0.
           0.        ]
         [ 1.39288319  1.00897299 -0.00376337 ...  0.          0.
           0.        ]
         [ 1.40628451  0.99183832  0.00200201 ...  0.          0.
           0.        ]
         ...
         [ 1.40030651  0.99571603 -0.00892139 ...  0.          0.
           0.        ]
         [ 1.39738134  0.99748994  0.0097489  ...  0.          0.
           0.        ]
         [ 1.40551371  0.99450414 -0.00399667 ...  0.          0.
           0.        ]]
_last_original_obs:
    value: None
_logger:
    value: <stable_baselines3.common.logger.Logger object at 0x1171de120>
_n_updates:
    value: 0
_num_timesteps_at_start:
    value: 0
_stats_window_size:
    value: 100
_total_timesteps:
    value: 1000000
_vec_normalize_env:
    value: None
_wandb:
    value:
        cli_version: 0.22.3
        e:
            aps9lvq10y0qd233fme6o8qxe6wpfcqt:
                apple:
                    ecpuCores: 4
                    gpuCores: 16
                    memoryGb: 24
                    name: Apple M4 Pro
                    pcpuCores: 8
                    ramTotalBytes: "25769803776"
                args:
                    - --env-id
                    - Humanoid-v5
                    - --total-timesteps
                    - "1000000"
                    - --n-envs
                    - "8"
                    - --wandb
                codePath: src/train.py
                codePathLocal: src/train.py
                cpu_count: 12
                cpu_count_logical: 12
                disk:
                    /:
                        total: "994662584320"
                        used: "357361831936"
                email: matteo.calabria01@gmail.com
                executable: /Users/matteo/Documents/01 Projects/hri-playground/.venv/bin/python3
                git:
                    commit: 2abc3a6bb618901dd999d3be592ddbd0266c4bfe
                    remote: git@github.com:maedmatt/hri-playground.git
                host: MacBookPro
                memory:
                    total: "25769803776"
                os: macOS-26.0.1-arm64-arm-64bit-Mach-O
                program: /Users/matteo/Documents/01 Projects/hri-playground/src/train.py
                python: CPython 3.13.8
                root: /Users/matteo/Documents/01 Projects/hri-playground
                startedAt: "2025-11-10T16:21:23.456758Z"
                writerId: aps9lvq10y0qd233fme6o8qxe6wpfcqt
        m: []
        python_version: 3.13.8
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 3
                - 13
                - 16
                - 22
                - 35
            "4": 3.13.8
            "5": 0.22.3
            "12": 0.22.3
            "13": darwin-arm64
action_noise:
    value: None
action_space:
    value: Box(-0.4, 0.4, (17,), float32)
algo:
    value: ppo
batch_size:
    value: 64
clip_range:
    value: FloatSchedule(ConstantSchedule(val=0.2))
clip_range_vf:
    value: None
device:
    value: cpu
ent_coef:
    value: 0
env:
    value: <stable_baselines3.common.vec_env.subproc_vec_env.SubprocVecEnv object at 0x114ddeba0>
env_id:
    value: Humanoid-v5
ep_info_buffer:
    value: deque([], maxlen=100)
ep_success_buffer:
    value: deque([], maxlen=100)
gae_lambda:
    value: 0.95
gamma:
    value: 0.99
learning_rate:
    value: 0.0003
lr_schedule:
    value: FloatSchedule(ConstantSchedule(val=0.0003))
max_grad_norm:
    value: 0.5
n_envs:
    value: 8
n_epochs:
    value: 10
n_steps:
    value: 2048
normalize_advantage:
    value: "True"
num_timesteps:
    value: 0
observation_space:
    value: Box(-inf, inf, (348,), float64)
policy:
    value: MlpPolicy
policy_class:
    value: <class 'stable_baselines3.common.policies.ActorCriticPolicy'>
policy_kwargs:
    value: '{}'
rollout_buffer:
    value: <stable_baselines3.common.buffers.RolloutBuffer object at 0x114e6c440>
rollout_buffer_class:
    value: <class 'stable_baselines3.common.buffers.RolloutBuffer'>
rollout_buffer_kwargs:
    value: '{}'
sde_sample_freq:
    value: -1
seed:
    value: 0
start_time:
    value: 1762791684347344000
target_kl:
    value: None
tensorboard_log:
    value: runs/tensorboard
total_timesteps:
    value: 1000000
use_sde:
    value: "False"
verbose:
    value: 0
vf_coef:
    value: 0.5
