_current_progress_remaining:
    value: 1
_custom_logger:
    value: "False"
_episode_num:
    value: 0
_last_episode_starts:
    value: '[ True]'
_last_obs:
    value: |-
        [[ 1.39081947e+00  9.90330553e-01  6.26540478e-03  8.25511155e-03
           2.13271552e-03  4.58993122e-03  8.72499829e-04  8.70144848e-03
           6.31707108e-03 -9.94523000e-03  7.14808553e-03 -9.32828849e-03
           4.59310893e-03 -6.48688759e-03  7.26357845e-03  8.29224405e-04
          -4.00576219e-03 -1.54625558e-03 -9.43360658e-03 -7.51433447e-03
           3.41248829e-03  2.94379023e-03  2.30770223e-03 -2.32644891e-03
           9.94419872e-03  9.61670678e-03  3.71083969e-03  3.00918553e-03
           3.76893461e-03 -2.22157152e-03 -7.29806990e-03  4.42976680e-03
           5.07086450e-04 -3.79516249e-03 -2.83292823e-04  7.78975669e-03
           8.68087032e-03 -2.84409607e-03  1.43059661e-03 -3.56261218e-03
           1.88600060e-03 -3.24177549e-03 -2.16761999e-03  7.80548704e-03
          -5.45684813e-03  2.30502147e+00  2.28589319e+00  4.25268224e-02
          -4.16369312e-04  2.72322701e-02  3.81968524e-02 -6.73185435e-02
          -7.52133893e-02  4.35721119e+00  8.90746237e+00  9.56419513e-02
           9.03895899e-02  1.08075018e-02 -1.61583780e-04  8.80551069e-03
           2.01832738e-03 -4.52246241e-02 -1.07665909e-02  4.40380624e-01
           2.26194671e+00  5.82661108e-02  4.20652728e-02  6.41351114e-02
          -3.11006534e-04  8.36756876e-03 -2.07247373e-04 -2.79458695e-01
          -1.31325508e-02  1.97978715e-01  6.61619413e+00  2.72167848e-01
           2.35307228e-01  5.08830264e-02 -1.06048744e-02 -2.24251901e-02
          -7.51638854e-02 -1.16955637e-01 -4.33460946e-01 -8.65634657e-01
           4.75175093e+00  9.27404289e-01  9.14580650e-01  2.19273281e-02
          -6.78141248e-03 -5.15786049e-02 -1.16881346e-01 -8.99598648e-02
          -2.08384775e-01 -1.55641189e+00  2.75569617e+00  1.04589488e+00
           1.03975128e+00  1.51910055e-02 -4.69123536e-03 -5.11854200e-02
          -9.46982528e-02 -6.69394228e-02 -1.23844766e-01 -1.35125311e+00
           1.76714587e+00  2.70311722e-01  2.29028000e-01  5.61146962e-02
           1.20845631e-02 -2.33481647e-02  8.11378536e-02 -1.24915105e-01
           4.60225690e-01 -8.46510550e-01  4.75175093e+00  9.26860279e-01
           9.03182211e-01  3.27158358e-02  8.81453773e-03 -5.07751536e-02
           1.52393397e-01 -8.96472643e-02  2.70711140e-01 -1.54629359e+00
           2.75569617e+00  1.04579412e+00  1.02982030e+00  2.44642740e-02
           6.41489319e-03 -4.80669439e-02  1.36605346e-01 -6.31568298e-02
           1.79490516e-01 -1.34492662e+00  1.76714587e+00  4.29136342e-01
           3.27988268e-01  1.30551622e-01  3.68453033e-02 -4.86367863e-02
           1.79348785e-01  1.24479155e-01 -4.28312187e-01  7.14713934e-01
           1.66108048e+00  3.18673829e-01  3.43653151e-01  1.86141525e-01
           8.30853261e-02 -1.57732538e-01  1.29042911e-01  3.51797962e-01
          -3.05779639e-01  5.35876429e-01  1.22954019e+00  4.23478748e-01
           3.34562876e-01  1.16959255e-01 -3.39867282e-02 -4.76895567e-02
          -1.70055559e-01  1.20602272e-01  4.02067332e-01  7.23209484e-01
           1.66108048e+00  3.14464281e-01  3.45658476e-01  1.74019491e-01
          -7.62940823e-02 -1.57056096e-01 -1.21918254e-01  3.46696597e-01
           2.86400166e-01  5.41660042e-01  1.22954019e+00  9.64993530e-03
           3.71497429e-03  2.89556432e-03  5.96218367e-04  2.07533440e-03
           1.00005597e-02  9.71731930e-03  1.44605474e-03  6.63557925e-03
           1.16453968e-03  2.16431051e-03  1.00442985e-02  2.41986560e-03
           1.38101833e-03  6.70460161e-03  1.17270320e-03  1.21925015e-03
           1.00169098e-02  6.84924854e-03 -2.38724686e-03  7.06458284e-03
           1.08964794e-03  1.17216028e-03  1.05459275e-02  6.84961648e-03
          -2.10406271e-03  7.07242006e-03  1.20085392e-03  1.17223595e-03
           1.05379726e-02  6.84961648e-03 -2.10406271e-03  7.07242006e-03
           1.20085392e-03  1.17223595e-03  1.05379726e-02 -5.40928631e-03
          -1.38618897e-03 -1.94908059e-03  2.93364317e-04  1.07941276e-03
           1.08571807e-02 -5.38748788e-03 -2.81641483e-03 -1.97327800e-03
          -2.68408199e-04  1.07016462e-03  1.08977288e-02 -5.38748788e-03
          -2.81641483e-03 -1.97327800e-03 -2.68408199e-04  1.07016462e-03
           1.08977288e-02  6.74689441e-03  9.20177417e-04  2.79227905e-03
           2.04644491e-03  5.87714821e-04  9.49252589e-03  6.70639346e-03
           3.23378550e-03  5.21885765e-04  2.09813914e-03  9.68271763e-04
           9.87940421e-03  7.96396598e-03  1.00866498e-02  7.60549671e-03
          -1.93606277e-03  1.22935293e-03  1.02385612e-02  8.03535553e-03
           1.39201676e-02  1.14883096e-02 -1.88379521e-03  5.93117284e-04
           1.08657584e-02  0.00000000e+00  0.00000000e+00  0.00000000e+00
           0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
           0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
           0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
           0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
           0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
           0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
           0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
           0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
           0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
           0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
           0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
           0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
           0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
           0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
           0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
           0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
           0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
           0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
           0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
           0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
           0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
           0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
           0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]]
_last_original_obs:
    value: None
_logger:
    value: <stable_baselines3.common.logger.Logger object at 0x115d10050>
_n_updates:
    value: 0
_num_timesteps_at_start:
    value: 0
_stats_window_size:
    value: 100
_total_timesteps:
    value: 500000
_vec_normalize_env:
    value: None
_wandb:
    value:
        cli_version: 0.22.3
        e:
            8b08lfbf6atsfuggnnykb11w2yzwgzlb:
                apple:
                    ecpuCores: 4
                    gpuCores: 16
                    memoryGb: 24
                    name: Apple M4 Pro
                    pcpuCores: 8
                    ramTotalBytes: "25769803776"
                args:
                    - --env-id
                    - Humanoid-v5
                    - --total-timesteps
                    - "500000"
                    - --wandb
                codePath: src/train.py
                codePathLocal: src/train.py
                cpu_count: 12
                cpu_count_logical: 12
                disk:
                    /:
                        total: "994662584320"
                        used: "340325126144"
                email: matteo.calabria01@gmail.com
                executable: /Users/matteo/Documents/01 Projects/hri-playground/.venv/bin/python3
                git:
                    commit: b789c0094ec4c66b7988fc5ff53043089284dfe7
                    remote: git@github.com:maedmatt/hri-playground.git
                host: MacBookPro
                memory:
                    total: "25769803776"
                os: macOS-26.0.1-arm64-arm-64bit-Mach-O
                program: /Users/matteo/Documents/01 Projects/hri-playground/src/train.py
                python: CPython 3.13.8
                root: /Users/matteo/Documents/01 Projects/hri-playground
                startedAt: "2025-11-10T10:34:33.507135Z"
                writerId: 8b08lfbf6atsfuggnnykb11w2yzwgzlb
        m: []
        python_version: 3.13.8
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 3
                - 13
                - 16
                - 22
                - 35
            "4": 3.13.8
            "5": 0.22.3
            "12": 0.22.3
            "13": darwin-arm64
action_noise:
    value: None
action_space:
    value: Box(-0.4, 0.4, (17,), float32)
algo:
    value: ppo
batch_size:
    value: 64
clip_range:
    value: FloatSchedule(ConstantSchedule(val=0.2))
clip_range_vf:
    value: None
device:
    value: cpu
ent_coef:
    value: 0
env:
    value: <stable_baselines3.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x1129aaba0>
env_id:
    value: Humanoid-v5
ep_info_buffer:
    value: deque([], maxlen=100)
ep_success_buffer:
    value: deque([], maxlen=100)
gae_lambda:
    value: 0.95
gamma:
    value: 0.99
learning_rate:
    value: 0.0003
lr_schedule:
    value: FloatSchedule(ConstantSchedule(val=0.0003))
max_grad_norm:
    value: 0.5
n_envs:
    value: 1
n_epochs:
    value: 10
n_steps:
    value: 2048
normalize_advantage:
    value: "True"
num_timesteps:
    value: 0
observation_space:
    value: Box(-inf, inf, (348,), float64)
policy:
    value: MlpPolicy
policy_class:
    value: <class 'stable_baselines3.common.policies.ActorCriticPolicy'>
policy_kwargs:
    value: '{}'
rollout_buffer:
    value: <stable_baselines3.common.buffers.RolloutBuffer object at 0x1135b9d30>
rollout_buffer_class:
    value: <class 'stable_baselines3.common.buffers.RolloutBuffer'>
rollout_buffer_kwargs:
    value: '{}'
sde_sample_freq:
    value: -1
seed:
    value: 0
start_time:
    value: 1762770874430150000
target_kl:
    value: None
tensorboard_log:
    value: runs/tensorboard
total_timesteps:
    value: 500000
use_sde:
    value: "False"
verbose:
    value: 0
vf_coef:
    value: 0.5
